version: "2"
services:
  www:
    build: ./nginx
    ports:
      - 4001:80
    restart: unless-stopped

  jenkins:
    image: jenkins:latest
    restart: unless-stopped
    user: root
    volumes:
      - /opt/jenkins:/var/jenkins_home
  sonarqube:
    image: sonarqube:latest
    restart: unless-stopped
    user: root
    links:
      - sonardb
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
    volumes:
      - /opt/sonarqube/data:/opt/sonarqube/data
      - /opt/sonarqube/extensions:/opt/sonarqube/extensions
  sonardb:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    restart: unless-stopped
    volumes:
      - /opt/sonardb:/var/lib/postgresql/data:rw
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - /opt/grafana/grafana:/var/lib/grafana:rw
  influxdb:
    build: ./influxdb
    volumes:
      - /opt/influxdb:/data
    ports:
      - 4002:2003/udp
    restart: unless-stopped
